### ISSUE TITLE
Permission to use pre-built ROMs

### ISSUE THREAD

**Issue by tamaroning** [Dillonb/n64-tests#1]
Hi, I am writing a N64 emulator.
I found this repository and want to use your ROMs as our testsuites.
This repository does not contain pre-built ROMs. So if I use `git submodule`, then we need to set up bulid environment like bass, chksum64, but I do not want to make build system complex.
So could you please give me permisson for my repo to contain your pre-built ROMs?
If so, I will write acknowledgement in my repo's README :) Thank you

**Comment by Dillonb** [comment]
Sure. Thanks for asking.
